# Generated by Django 5.1.7 on 2025-08-13 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(limit_choices_to={'user_role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_given', to=settings.AUTH_USER_MODEL, verbose_name='추천한 학생')),
                ('to_user', models.ForeignKey(limit_choices_to={'user_role': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to=settings.AUTH_USER_MODEL, verbose_name='추천 받은 사장님')),
            ],
            options={
                'verbose_name': '추천',
                'verbose_name_plural': '추천들',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='recommended_targets',
            field=models.ManyToManyField(blank=True, related_name='recommended_by', through='accounts.Recommendation', to=settings.AUTH_USER_MODEL, verbose_name='추천 대상(사장님)'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['to_user'], name='accounts_re_to_user_5e121e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['from_user', 'to_user'], name='accounts_re_from_us_a57381_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='uq_recommend_from_to'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='ck_recommend_no_self'),
        ),
    ]
