# Generated by Django 5.1.7 on 2025-08-16 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=100, verbose_name='발신인(표시용)')),
                ('recipient_display_name', models.CharField(blank=True, max_length=100, verbose_name='수신자 표시명(스냅샷)')),
                ('title', models.CharField(max_length=120, verbose_name='제안 제목')),
                ('contents', models.TextField(verbose_name='요청 개요')),
                ('partnership_purpose', models.TextField(verbose_name='제휴 목적')),
                ('expected_effects', models.TextField(verbose_name='기대 효과')),
                ('contact_info', models.CharField(max_length=200, verbose_name='연락처')),
                ('apply_target', models.CharField(choices=[('STUDENTS', '대학생 전체'), ('GROUP_MEMBERS', '학생단체 구성원'), ('ALL_CUSTOMERS', '모든 손님'), ('OTHER', '기타')], db_index=True, default='GROUP_MEMBERS', max_length=40, verbose_name='적용 대상')),
                ('apply_target_other', models.CharField(blank=True, max_length=200, verbose_name='적용 대상(기타 상세)')),
                ('time_windows', models.JSONField(blank=True, default=list, verbose_name='적용 시간대')),
                ('benefit_type', models.CharField(choices=[('PERCENT_DISCOUNT', '퍼센트 할인'), ('AMOUNT_DISCOUNT', '정액 할인'), ('FREE_ITEM', '무료 제공'), ('OTHER', '기타')], db_index=True, default='PERCENT_DISCOUNT', max_length=30, verbose_name='혜택 유형')),
                ('benefit_description', models.CharField(blank=True, max_length=250, verbose_name='혜택 상세 설명(예: 무료 음료 1잔)')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='제휴 시작일')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='제휴 종료일')),
                ('min_order_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='최소 결제 금액(원)')),
                ('max_redemptions_per_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='1인 최대 사용 횟수')),
                ('max_total_redemptions', models.PositiveIntegerField(blank=True, null=True, verbose_name='전체 최대 사용 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('author', models.ForeignKey(limit_choices_to={'user_role__in': ['STUDENT_GROUP', 'OWNER']}, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_authored', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('recipient', models.ForeignKey(limit_choices_to={'user_role__in': ['STUDENT_GROUP', 'OWNER']}, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_received', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '제안서',
                'verbose_name_plural': '제안서들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNREAD', '미열람'), ('READ', '열람'), ('PARTNERSHIP', '제휴체결'), ('REJECTED', '거절')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_status_changes', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='proposals.proposal')),
            ],
            options={
                'verbose_name': '제안서 상태',
                'verbose_name_plural': '제안서 상태 히스토리',
                'ordering': ['-changed_at'],
                'get_latest_by': 'changed_at',
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['recipient'], name='proposals_p_recipie_3e34f8_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['author', 'recipient'], name='proposals_p_author__62389b_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(condition=models.Q(('author', models.F('recipient')), _negated=True), name='ck_proposal_no_self'),
        ),
        migrations.AddIndex(
            model_name='proposalstatus',
            index=models.Index(fields=['proposal', 'changed_at'], name='proposals_p_proposa_eda4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalstatus',
            index=models.Index(fields=['status'], name='proposals_p_status_1d2f07_idx'),
        ),
    ]
