# Generated by Django 5.1.7 on 2025-08-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='max_redemptions_per_user',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='max_total_redemptions',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='min_order_amount',
        ),
    ]
