# Generated by Django 5.1.7 on 2025-08-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_remove_proposal_max_redemptions_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='partnership_purpose',
        ),
    ]
