# Generated by Django 5.1.7 on 2025-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_remove_proposal_partnership_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='partnership_type',
            field=models.JSONField(blank=True, default=list, help_text='할인형, 리뷰형, 서비스제공형, 타임형 중 하나 이상', verbose_name='제휴 방식'),
        ),
    ]
