# Generated by Django 5.1.7 on 2025-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_partnership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='apply_target_other',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='benefit_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='title',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='apply_target',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='적용 대상'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='expected_effects',
            field=models.TextField(blank=True, verbose_name='기대 효과'),
        ),
    ]
