# Generated by Django 5.1.7 on 2025-08-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_remove_proposal_apply_target_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='status',
            field=models.CharField(choices=[('UNREAD', '미열람'), ('READ', '열람'), ('PARTNERSHIP', '제휴체결'), ('REJECTED', '거절'), ('DRAFT', '초안')], max_length=20),
        ),
    ]
