# Generated by Django 5.1.7 on 2025-08-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_alter_proposalstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='apply_target',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='적용 대상'),
        ),
    ]
