# Generated by Django 5.2.4 on 2025-08-12 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(blank=True, help_text='검색으로 선택한 캠퍼스명', max_length=100, null=True, verbose_name='대학교명')),
                ('business_type', models.CharField(choices=[('RESTAURANT', '식당'), ('CAFE', '카페'), ('BAR', '주점')], db_index=True, help_text='식당, 카페, 주점 중 하나', max_length=20, verbose_name='업종')),
                ('profile_name', models.CharField(max_length=30)),
                ('business_day', models.JSONField(default=dict, help_text='요일별 시간대 배열 JSON')),
                ('partnership_goal', models.CharField(choices=[('NEW_CUSTOMERS', '신규 고객 유입'), ('REVISIT', '재방문 증가'), ('CLEAR_STOCK', '재고 소진'), ('SPREAD_PEAK', '피크타임 분산'), ('SNS_MARKETING', 'SNS 홍보'), ('COLLECT_REVIEWS', '리뷰 확보'), ('OTHER', '기타')], db_index=True, help_text='신규 고객 유입, 재방문 증가, 재고 소진, 피크타임 분산, SNS 홍보, 리뷰 확보, 기타 중 하나', max_length=20, verbose_name='제휴 목표')),
                ('partnership_goal_other', models.CharField(blank=True, help_text='제휴 목표가 기타(OTHER)일 때 상세', max_length=200, verbose_name='기타 상세')),
                ('average_sales', models.PositiveIntegerField(help_text='원 단위', validators=[django.core.validators.MinValueValidator(0)])),
                ('margin_rate', models.DecimalField(decimal_places=2, help_text='0~100 사이 퍼센트', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('peak_time', models.JSONField(blank=True, default=list, help_text='문자열 구간 배열')),
                ('off_peak_time', models.JSONField(blank=True, default=list, help_text='문자열 구간 배열')),
                ('available_service', models.CharField(choices=[('SIDE_MENU', '사이드 메뉴'), ('DRINK', '음료수'), ('OTHERS', '기타')], db_index=True, help_text='음료수, 사이드 메뉴, 기타 중 하나', max_length=20, verbose_name='추가 제공 가능 서비스')),
                ('available_service_other', models.CharField(blank=True, help_text='추가 제공 가능 서비스가 기타(OTHER)일 때 상세', max_length=200, verbose_name='기타 상세')),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('partnership_type', models.JSONField(blank=True, default=list, help_text='할인형, 리뷰형, 서비스제공형, 타임형 중 하나 이상')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='owner_profile/photos/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='표시 순서')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('owner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.ownerprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, help_text='검색으로 선택한 대학교명 (예: 서울대학교)', max_length=100, null=True, verbose_name='소속대학교명')),
                ('council_name', models.CharField(blank=True, help_text='소속된 학생회', max_length=100, null=True)),
                ('position', models.CharField(max_length=30)),
                ('student_size', models.PositiveIntegerField(help_text='명 단위', validators=[django.core.validators.MinValueValidator(0)])),
                ('term_start', models.DateField(verbose_name='임기 시작일')),
                ('term_end', models.DateField(verbose_name='임기 종료일')),
                ('partnership_start', models.DateField(verbose_name='제휴 시작일')),
                ('partnership_end', models.DateField(verbose_name='제휴 종료일')),
                ('partnership_record', models.CharField(choices=[('TRUE', '있음'), ('FALSE', '없음')], db_index=True, help_text='있음, 없음 중 하나', max_length=5, verbose_name='제휴 이력')),
                ('record_name', models.CharField(blank=True, max_length=100, verbose_name='제휴 업체명')),
                ('record_start', models.DateField(verbose_name='제휴 시작일')),
                ('record_end', models.DateField(verbose_name='제휴 종료일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_group_profile/photos/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='표시 순서')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('student_group_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.studentgroupprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, help_text='검색으로 선택한 캠퍼스명', max_length=100, null=True, verbose_name='대학교명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_profile/image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='owner_profile/menus/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='표시 순서')),
                ('owner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='profiles.ownerprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('owner_profile', 'name')},
            },
        ),
    ]
