# Generated by Django 5.2.4 on 2025-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroupprofile',
            name='partnership_record',
        ),
        migrations.RemoveField(
            model_name='studentgroupprofile',
            name='record_end',
        ),
        migrations.RemoveField(
            model_name='studentgroupprofile',
            name='record_name',
        ),
        migrations.RemoveField(
            model_name='studentgroupprofile',
            name='record_start',
        ),
        migrations.AddField(
            model_name='studentgroupprofile',
            name='partnership_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='comment',
            field=models.CharField(max_length=25),
        ),
    ]
