# Generated by Django 5.2.4 on 2025-08-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='off_peak_time',
            field=models.JSONField(blank=True, default=dict, help_text='요일별 시간대 배열 JSON', null=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='peak_time',
            field=models.JSONField(blank=True, default=dict, help_text='요일별 시간대 배열 JSON', null=True),
        ),
        migrations.AlterField(
            model_name='studentgroupprofile',
            name='council_name',
            field=models.CharField(blank=True, help_text='학생회명', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroupprofile',
            name='department',
            field=models.CharField(blank=True, help_text='소속', max_length=100, null=True),
        ),
    ]
