# Generated by Django 5.2.4 on 2025-08-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_studentgroupprofile_partnership_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='이름'),
        ),
    ]
