# Generated by Django 5.2.4 on 2025-08-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_studentprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='off_peak_time',
            field=models.JSONField(default=dict, help_text='요일별 시간대 배열 JSON'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='peak_time',
            field=models.JSONField(default=dict, help_text='요일별 시간대 배열 JSON'),
        ),
    ]
