# Generated by Django 5.2.4 on 2025-08-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_ownerprofile_off_peak_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='partnership_type',
        ),
    ]
