# Generated by Django 5.2.4 on 2025-08-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_ownerprofile_partnership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupprofile',
            name='department',
            field=models.CharField(blank=True, help_text='학생회명', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentgroupprofile',
            name='council_name',
            field=models.CharField(blank=True, help_text='소속', max_length=100, null=True),
        ),
    ]
