# Generated by Django 5.2.4 on 2025-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_studentgroupprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='studentgroupprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='comment',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
