# Generated by Django 5.2.4 on 2025-08-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_ownerprofile_contact_studentgroupprofile_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='available_service',
            field=models.JSONField(default=list, help_text='음료수, 사이드 메뉴, 기타 중 하나', verbose_name='추가 제공 가능 서비스'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='available_service_other',
            field=models.CharField(blank=True, help_text='제공 가능 서비스 리스트 예: ["DRINK", "SIDE_MENU"]', max_length=200, verbose_name='기타 상세'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='partnership_goal',
            field=models.JSONField(default=list, help_text='제휴 목표 리스트 예: ["NEW_CUSTOMERS", "REVISIT"]', verbose_name='제휴 목표'),
        ),
    ]
