# Generated by Django 5.2.4 on 2025-08-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_ownerprofile_available_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='available_service',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='available_service_other',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='service_drink',
            field=models.BooleanField(default=False, verbose_name='음료수 제공'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='service_other',
            field=models.BooleanField(default=False, verbose_name='기타 서비스 제공'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='service_other_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='기타 서비스 상세'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='service_side_menu',
            field=models.BooleanField(default=False, verbose_name='사이드 메뉴 제공'),
        ),
    ]
