# Generated by Django 5.2.4 on 2025-08-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_ownerprofile_available_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='partnership_goal',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='partnership_goal_other',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='goal_clear_stock',
            field=models.BooleanField(default=False, verbose_name='재고 소진'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='goal_collect_reviews',
            field=models.BooleanField(default=False, verbose_name='리뷰 확보'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='goal_new_customers',
            field=models.BooleanField(default=False, verbose_name='신규 고객 유입'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='goal_other',
            field=models.BooleanField(default=False, verbose_name='기타'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='goal_other_detail',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타 상세'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='goal_revisit',
            field=models.BooleanField(default=False, verbose_name='재방문 증가'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='goal_sns_marketing',
            field=models.BooleanField(default=False, verbose_name='SNS 홍보'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='goal_spread_peak',
            field=models.BooleanField(default=False, verbose_name='피크타임 분산'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='service_other_detail',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기타 서비스 상세'),
        ),
    ]
