# Generated by Django 5.2.4 on 2025-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_ownerprofile_partnership_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='business_type_other',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='기타 업종 상세'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='business_type',
            field=models.CharField(choices=[('RESTAURANT', '식당'), ('CAFE', '카페'), ('BAR', '주점'), ('OTHER', '기타')], db_index=True, help_text='식당, 카페, 주점 중 하나', max_length=20, verbose_name='업종'),
        ),
    ]
